/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Techsoft;

/**
 *
 * @author santi
 */
public class main_GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(main_GUI.class.getName());

    /**
     * Creates new form main_GUI
     */


    public main_GUI() {
        setUndecorated(true);   
        initComponents();
        setSize(400, 700);
        setLocationRelativeTo(null); 
        setResizable(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is alwaysA
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMainPanel = new javax.swing.JPanel();
        jMainCenter = new javax.swing.JPanel();
        jNavMain = new javax.swing.JPanel();
        jFooterMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        register_employee = new javax.swing.JButton();
        search_employee = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 700));

        jMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        jMainPanel.setLayout(new java.awt.BorderLayout());

        jMainCenter.setBackground(new java.awt.Color(102, 102, 102));

        jNavMain.setBackground(new java.awt.Color(51, 51, 51));
        jNavMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jNavMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jNavMainLayout = new javax.swing.GroupLayout(jNavMain);
        jNavMain.setLayout(jNavMainLayout);
        jNavMainLayout.setHorizontalGroup(
            jNavMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        jNavMainLayout.setVerticalGroup(
            jNavMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        jFooterMain.setBackground(new java.awt.Color(51, 51, 51));
        jFooterMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jFooterMainLayout = new javax.swing.GroupLayout(jFooterMain);
        jFooterMain.setLayout(jFooterMainLayout);
        jFooterMainLayout.setHorizontalGroup(
            jFooterMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jFooterMainLayout.setVerticalGroup(
            jFooterMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome, ");

        register_employee.setBackground(new java.awt.Color(51, 51, 51));
        register_employee.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        register_employee.setForeground(new java.awt.Color(255, 255, 255));
        register_employee.setText("Register employee");
        register_employee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register_employee.addActionListener(this::register_employeeActionPerformed);

        search_employee.setBackground(new java.awt.Color(51, 51, 51));
        search_employee.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        search_employee.setForeground(new java.awt.Color(255, 255, 255));
        search_employee.setText("Search employee");
        search_employee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_employee.addActionListener(this::search_employeeActionPerformed);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Logo_techsoft1.png"))); // NOI18N
        jLabelLogo.setMaximumSize(new java.awt.Dimension(1024, 1024));
        jLabelLogo.setMinimumSize(new java.awt.Dimension(1024, 1024));
        jLabelLogo.setPreferredSize(new java.awt.Dimension(1024, 1024));

        javax.swing.GroupLayout jMainCenterLayout = new javax.swing.GroupLayout(jMainCenter);
        jMainCenter.setLayout(jMainCenterLayout);
        jMainCenterLayout.setHorizontalGroup(
            jMainCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFooterMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jNavMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jMainCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMainCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMainCenterLayout.createSequentialGroup()
                        .addComponent(register_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jMainCenterLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jMainCenterLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jMainCenterLayout.setVerticalGroup(
            jMainCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainCenterLayout.createSequentialGroup()
                .addComponent(jNavMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jMainCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jFooterMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMainPanel.add(jMainCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_employeeActionPerformed
        // TODO add your handling code here:
        
       search_GUI menu = new search_GUI();
       menu.setVisible(true);
       dispose();

    }//GEN-LAST:event_search_employeeActionPerformed

    private void register_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_employeeActionPerformed
        // TODO add your handling code here:
        
        register_GUI menu = new register_GUI();
        menu.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_register_employeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new main_GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jFooterMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jMainCenter;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jNavMain;
    private javax.swing.JButton register_employee;
    private javax.swing.JButton search_employee;
    // End of variables declaration//GEN-END:variables
}
