/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Techsoft;

import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author santi
 */
public class register_GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(register_GUI.class.getName());

    /**
     * Creates new form main_GUI
     */


    public register_GUI() {
        setUndecorated(true);   
        initComponents();
        setSize(400, 700);
        setLocationRelativeTo(null); 
        setResizable(false);
        
        loadRoles();          
        setAutomaticDate();   
        roleSalaryListener(); 
    }
    
        private void loadRoles() {
        ComboRole.removeAllItems();

        ComboRole.addItem("Software Engineer");
        ComboRole.addItem("Frontend Developer");
        ComboRole.addItem("Backend Developer");
        ComboRole.addItem("QA Engineer");
        ComboRole.addItem("Project Manager");
    }
        
        private void roleSalaryListener() {

        ComboRole.addActionListener(e -> {

        String roleSelected = ComboRole.getSelectedItem().toString();
        double salary = 0;

        switch (roleSelected) {
            case "Software Engineer" -> salary = 6000000;
            case "Frontend Developer" -> salary = 4500000;
            case "Backend Developer" -> salary = 5000000;
            case "QA Engineer" -> salary = 4000000;
            case "Project Manager" -> salary = 8000000;
        }

        jTextField6.setText(String.valueOf(salary));
    });
}
        
    private void setAutomaticDate() {

    LocalDate tomorrow = LocalDate.now().plusDays(1);
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    textStartDate.setText(tomorrow.format(formatter));
    textStartDate.setEditable(false);
}


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMainPanel = new javax.swing.JPanel();
        jMainCenter = new javax.swing.JPanel();
        jNavMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFooterMain = new javax.swing.JPanel();
        pIdDocument = new javax.swing.JPanel();
        jIdDocument = new javax.swing.JLabel();
        textIdNumebr = new javax.swing.JTextField();
        pName = new javax.swing.JPanel();
        jName = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        pAge = new javax.swing.JPanel();
        jAge = new javax.swing.JLabel();
        textAge = new javax.swing.JTextField();
        pRole = new javax.swing.JPanel();
        jRole = new javax.swing.JLabel();
        ComboRole = new javax.swing.JComboBox<>();
        pSalary = new javax.swing.JPanel();
        jSalary = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        pStartDate = new javax.swing.JPanel();
        jStartDate = new javax.swing.JLabel();
        textStartDate = new javax.swing.JTextField();
        ButtonSend = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        jMainPanel.setLayout(new java.awt.BorderLayout());

        jMainCenter.setBackground(new java.awt.Color(102, 102, 102));

        jNavMain.setBackground(new java.awt.Color(51, 51, 51));
        jNavMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jNavMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register a new employee");

        javax.swing.GroupLayout jNavMainLayout = new javax.swing.GroupLayout(jNavMain);
        jNavMain.setLayout(jNavMainLayout);
        jNavMainLayout.setHorizontalGroup(
            jNavMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNavMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jNavMainLayout.setVerticalGroup(
            jNavMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNavMainLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jFooterMain.setBackground(new java.awt.Color(51, 51, 51));
        jFooterMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jFooterMainLayout = new javax.swing.GroupLayout(jFooterMain);
        jFooterMain.setLayout(jFooterMainLayout);
        jFooterMainLayout.setHorizontalGroup(
            jFooterMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jFooterMainLayout.setVerticalGroup(
            jFooterMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        pIdDocument.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pIdDocument.setPreferredSize(new java.awt.Dimension(388, 50));

        jIdDocument.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jIdDocument.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jIdDocument.setText("Document number");
        jIdDocument.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textIdNumebr.addActionListener(this::textIdNumebrActionPerformed);

        javax.swing.GroupLayout pIdDocumentLayout = new javax.swing.GroupLayout(pIdDocument);
        pIdDocument.setLayout(pIdDocumentLayout);
        pIdDocumentLayout.setHorizontalGroup(
            pIdDocumentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jIdDocument, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(textIdNumebr)
        );
        pIdDocumentLayout.setVerticalGroup(
            pIdDocumentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIdDocumentLayout.createSequentialGroup()
                .addComponent(jIdDocument)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textIdNumebr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pName.setPreferredSize(new java.awt.Dimension(388, 50));

        jName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jName.setText("Name");
        jName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textName.addActionListener(this::textNameActionPerformed);

        javax.swing.GroupLayout pNameLayout = new javax.swing.GroupLayout(pName);
        pName.setLayout(pNameLayout);
        pNameLayout.setHorizontalGroup(
            pNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jName, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(textName)
        );
        pNameLayout.setVerticalGroup(
            pNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNameLayout.createSequentialGroup()
                .addComponent(jName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pAge.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pAge.setPreferredSize(new java.awt.Dimension(388, 50));

        jAge.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAge.setText("Age");
        jAge.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textAge.addActionListener(this::textAgeActionPerformed);

        javax.swing.GroupLayout pAgeLayout = new javax.swing.GroupLayout(pAge);
        pAge.setLayout(pAgeLayout);
        pAgeLayout.setHorizontalGroup(
            pAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAge, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(textAge)
        );
        pAgeLayout.setVerticalGroup(
            pAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAgeLayout.createSequentialGroup()
                .addComponent(jAge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pRole.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pRole.setPreferredSize(new java.awt.Dimension(388, 50));

        jRole.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRole.setText("Role");
        jRole.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ComboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboRole.addActionListener(this::ComboRoleActionPerformed);

        javax.swing.GroupLayout pRoleLayout = new javax.swing.GroupLayout(pRole);
        pRole.setLayout(pRoleLayout);
        pRoleLayout.setHorizontalGroup(
            pRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRole, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addGroup(pRoleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pRoleLayout.setVerticalGroup(
            pRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRoleLayout.createSequentialGroup()
                .addComponent(jRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(ComboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pSalary.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pSalary.setPreferredSize(new java.awt.Dimension(388, 50));

        jSalary.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jSalary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSalary.setText("Salary");
        jSalary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextField6.addActionListener(this::jTextField6ActionPerformed);

        javax.swing.GroupLayout pSalaryLayout = new javax.swing.GroupLayout(pSalary);
        pSalary.setLayout(pSalaryLayout);
        pSalaryLayout.setHorizontalGroup(
            pSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(jTextField6)
        );
        pSalaryLayout.setVerticalGroup(
            pSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSalaryLayout.createSequentialGroup()
                .addComponent(jSalary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pStartDate.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pStartDate.setPreferredSize(new java.awt.Dimension(388, 50));

        jStartDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jStartDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jStartDate.setText("Start ");
        jStartDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textStartDate.addActionListener(this::textStartDateActionPerformed);

        javax.swing.GroupLayout pStartDateLayout = new javax.swing.GroupLayout(pStartDate);
        pStartDate.setLayout(pStartDateLayout);
        pStartDateLayout.setHorizontalGroup(
            pStartDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(textStartDate)
        );
        pStartDateLayout.setVerticalGroup(
            pStartDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStartDateLayout.createSequentialGroup()
                .addComponent(jStartDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonSend.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonSend.setText("Finish");
        ButtonSend.addActionListener(this::ButtonSendActionPerformed);

        javax.swing.GroupLayout jMainCenterLayout = new javax.swing.GroupLayout(jMainCenter);
        jMainCenter.setLayout(jMainCenterLayout);
        jMainCenterLayout.setHorizontalGroup(
            jMainCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFooterMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jNavMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jMainCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMainCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainCenterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jMainCenterLayout.createSequentialGroup()
                        .addGroup(jMainCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pIdDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ButtonSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jMainCenterLayout.setVerticalGroup(
            jMainCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainCenterLayout.createSequentialGroup()
                .addComponent(jNavMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pIdDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(ButtonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jFooterMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMainPanel.add(jMainCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textIdNumebrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdNumebrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdNumebrActionPerformed

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void textAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAgeActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void textStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStartDateActionPerformed

    private void ButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSendActionPerformed
        String idDocument;
        String name;
        int age;
        String role;
        double salary;
        String startDate;

        try {
            idDocument = textIdNumebr.getText().trim();
            if (idDocument.isEmpty() || !idDocument.matches("\\d+"))
                throw new Exception();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato incorrecto en Document", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            name = textName.getText().trim();
            if (name.isEmpty() || !name.matches("[a-zA-Z ]+"))
                throw new Exception();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato incorrecto en Name", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            age = Integer.parseInt(textAge.getText().trim());
            if (age <= 17)
                throw new Exception();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato incorrecto en Age", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            role = ComboRole.getSelectedItem().toString();
            if (role.isEmpty())
                throw new Exception();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato incorrecto en Role", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            salary = Double.parseDouble(jTextField6.getText().trim());
            if (salary <= 0)
                throw new Exception();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato incorrecto en Salary", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            startDate = textStartDate.getText().trim();
            if (startDate.isEmpty())
                throw new Exception();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato incorrecto en Start Date", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        //Employee dato = new Employee(idDocument, name, age, role, salary, startDate);
        //EmployeeList.add(dato);   // tu lista
        //FileManager.saveToFile(EmployeeList); // tu método
        //JOptionPane.showMessageDialog(this, "Employee registered successfully");
    }//GEN-LAST:event_ButtonSendActionPerformed

    private void ComboRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboRoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new main_GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSend;
    private javax.swing.JComboBox<String> ComboRole;
    private javax.swing.JLabel jAge;
    private javax.swing.JPanel jFooterMain;
    private javax.swing.JLabel jIdDocument;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jMainCenter;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jName4;
    private javax.swing.JLabel jName5;
    private javax.swing.JPanel jNavMain;
    private javax.swing.JLabel jRole;
    private javax.swing.JLabel jSalary;
    private javax.swing.JLabel jStartDate;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel pAge;
    private javax.swing.JPanel pIdDocument;
    private javax.swing.JPanel pIdDocument4;
    private javax.swing.JPanel pIdDocument5;
    private javax.swing.JPanel pName;
    private javax.swing.JPanel pRole;
    private javax.swing.JPanel pSalary;
    private javax.swing.JPanel pStartDate;
    private javax.swing.JTextField textAge;
    private javax.swing.JTextField textIdNumebr;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textStartDate;
    // End of variables declaration//GEN-END:variables
}
