/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Techsoft;

/**
 *
 * @author santi
 */
public class search_GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(search_GUI.class.getName());

    /**
     * Creates new form search_GUI
     */
    public search_GUI() {

        setUndecorated(true);   
        initComponents();
        setSize(400, 700);
        setLocationRelativeTo(null); 
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainPanel = new javax.swing.JPanel();
        jMainCenter = new javax.swing.JPanel();
        jNavMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jFooterMain = new javax.swing.JPanel();
        pIdDocument = new javax.swing.JPanel();
        jIdDocument = new javax.swing.JLabel();
        textIdNumebr = new javax.swing.JTextField();
        ButtonSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        jMainPanel.setLayout(new java.awt.BorderLayout());

        jMainCenter.setBackground(new java.awt.Color(102, 102, 102));

        jNavMain.setBackground(new java.awt.Color(51, 51, 51));
        jNavMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jNavMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search a employee");

        Back.setBackground(new java.awt.Color(51, 51, 51));
        Back.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("<--");
        Back.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Back.addActionListener(this::BackActionPerformed);

        javax.swing.GroupLayout jNavMainLayout = new javax.swing.GroupLayout(jNavMain);
        jNavMain.setLayout(jNavMainLayout);
        jNavMainLayout.setHorizontalGroup(
            jNavMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNavMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jNavMainLayout.setVerticalGroup(
            jNavMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNavMainLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jNavMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Back))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jFooterMain.setBackground(new java.awt.Color(51, 51, 51));
        jFooterMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jFooterMainLayout = new javax.swing.GroupLayout(jFooterMain);
        jFooterMain.setLayout(jFooterMainLayout);
        jFooterMainLayout.setHorizontalGroup(
            jFooterMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jFooterMainLayout.setVerticalGroup(
            jFooterMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        pIdDocument.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pIdDocument.setPreferredSize(new java.awt.Dimension(388, 50));

        jIdDocument.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jIdDocument.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jIdDocument.setText("Document number");
        jIdDocument.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textIdNumebr.addActionListener(this::textIdNumebrActionPerformed);

        javax.swing.GroupLayout pIdDocumentLayout = new javax.swing.GroupLayout(pIdDocument);
        pIdDocument.setLayout(pIdDocumentLayout);
        pIdDocumentLayout.setHorizontalGroup(
            pIdDocumentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jIdDocument, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(textIdNumebr)
        );
        pIdDocumentLayout.setVerticalGroup(
            pIdDocumentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIdDocumentLayout.createSequentialGroup()
                .addComponent(jIdDocument)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textIdNumebr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonSearch.setText("Search employee");
        ButtonSearch.addActionListener(this::ButtonSearchActionPerformed);

        javax.swing.GroupLayout jMainCenterLayout = new javax.swing.GroupLayout(jMainCenter);
        jMainCenter.setLayout(jMainCenterLayout);
        jMainCenterLayout.setHorizontalGroup(
            jMainCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFooterMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jNavMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jMainCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMainCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jMainCenterLayout.createSequentialGroup()
                        .addComponent(pIdDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jMainCenterLayout.setVerticalGroup(
            jMainCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainCenterLayout.createSequentialGroup()
                .addComponent(jNavMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addComponent(pIdDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFooterMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMainPanel.add(jMainCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        main_GUI main = new main_GUI();
        main.setVisible(true);
        dispose();

    }//GEN-LAST:event_BackActionPerformed

    private void textIdNumebrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdNumebrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdNumebrActionPerformed

    private void ButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchActionPerformed

       
    }//GEN-LAST:event_ButtonSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new search_GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton ButtonSearch;
    private javax.swing.JPanel jFooterMain;
    private javax.swing.JLabel jIdDocument;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jMainCenter;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JPanel jNavMain;
    private javax.swing.JPanel pIdDocument;
    private javax.swing.JTextField textIdNumebr;
    // End of variables declaration//GEN-END:variables
}
